export const Currencies = {
    BTC: 'Bitcoin',
    ETH: 'Ethereum',
    BNB: 'Binance Coin',
    SOL: 'SOL RUNE - Rune.Game',
    ADA: 'Cardano',
    XRP: 'XRP',
    DOT: 'Polkadot',
    USDC: 'USD Coin',
    DOGE: 'Dogecoin',
    AVAX: 'Avalanche',
    SHIB: 'SHIBA INU',
    LUNA: 'Luna Coin',
    LTC: 'Litecoin',
    UNI: 'UNICORN Token',
    BUSD: 'Binance USD',
    LINK: 'Chainlink',
    MATIC: 'Polygon',
    ALGO: 'Algorand',
    BCH: 'Bitcoin Cash',
    EGLD: 'Elrond',
    XLM: 'Stellar',
    MANA: 'Genesis Mana',
    AXS: 'Axie Infinity',
    VET: 'VeChain',
    ICP: 'Internet Computer',
    TRX: 'TRON',
    FTT: 'FTX Token',
    ATOM: 'Cosmos',
    THETA: 'THETA',
    DAI: 'Dai',
    FIL: 'Filecoin',
    ETC: 'Ethereum Classic',
    SAND: 'The Sandbox',
    FTM: 'Fantom',
    HBAR: 'Hedera',
    NEAR: 'NEAR Protocol',
    HNT: 'Helium',
    XMR: 'Monero',
    XTZ: 'Tezos',
    GRT: 'Golden Ratio Token',
    LRC: 'Loopring',
    EOS: 'EOS',
    FLOW: 'Flow',
    KLAY: 'Klaytn',
    CAKE: 'PancakeSwap',
    ENJ: 'Enjin Coin',
    AAVE: 'Aave',
    ONE: 'BigONE Token',
    ZEC: 'Zcash',
    GALA: 'Gala',
    MKR: 'Maker',
    XEC: 'eCash',
    KSM: 'Kusama',
    RUNE: 'THORChain (ERC20)',
    QNT: 'Quant',
    NEO: 'Neo',
    AMP: 'Amp',
    CHZ: 'Chiliz',
    STX: 'Stox',
    HOT: 'Hydro Protocol',
    WAVES: 'Waves',
    BTT: 'BitTorrent',
    DASH: 'Dash',
    CRV: 'Curve DAO Token',
    AR: 'Arweave',
    CELO: 'Celo',
    IOTX: 'IoTeX',
    COMP: 'Compound Coin',
    TFUEL: 'Theta Fuel',
    BAT: 'Basic Attention Token',
    XEM: 'NEM',
    WAXP: 'WAX',
    DCR: 'Decred',
    ROSE: 'Oasis Network',
    QTUM: 'Qtum',
    ZEN: 'Horizen',
    ICX: 'ICON',
    MINA: 'Mina',
    AUDIO: 'Audius',
    TUSD: 'TrueUSD',
    OMG: 'OMG Network',
    VGX: 'Voyager Token',
    RVN: 'Ravencoin',
    YFI: 'yearn.finance',
    ZIL: 'Zilliqa',
    SUSHI: 'SushiSwap',
    PERP: 'Perpetual Protocol',
    LPT: 'Livepeer',
    ANKR: 'Ankr',
    BTG: 'Bitcoin Gold',
    SC: 'Siacoin',
    USDP: 'USDP Stablecoin',
    BNT: 'Bancor',
    SNX: 'Synthetix',
    UMA: 'UMA',
    ZRX: '0x',
    REN: 'Ren',
    SKL: 'SKALE Network',
    MOVR: 'Moonriver',
    DYDX: 'dYdX',
    ONT: 'Ontology',
    CELR: 'Celer Network',
    WIN: 'WINkLink',
    RAY: 'Raydium',
    KAVA: 'Kava',
    SRM: 'Serum',
    IOST: 'IOST',
    STORJ: 'Storj',
    DGB: 'DigiByte',
    CHR: 'Chromia',
    ALICE: 'MyNeighborAlice',
    '1INCH': '1inch Network',
    CKB: 'Nervos Network',
    NANO: 'Nano',
    POLY: 'FarmPoly',
    OCEAN: 'Ocean Protocol',
    GNO: 'Gnosis',
    FET: 'Fetch.ai',
    INJ: 'Injective Protocol',
    NU: 'NuCypher',
    MDX: 'Mandala Exchange Token',
    HIVE: 'Hive',
    DENT: 'Dent',
    RSR: 'Reserve Rights',
    CTSI: 'Cartesi',
    SXP: 'Swipe',
    LSK: 'Lisk',
    REEF: 'Reef',
    ALPHA: 'PolyAlpha Finance',
    XVG: 'Verge',
    OGN: 'Origin Protocol',
    WRX: 'WazirX',
    VTHO: 'VeThor Token',
    NKN: 'NKN',
    COTI: 'COTI',
    BAKE: 'BakeryToken',
    BTCST: 'Bitcoin Standard Hashrate Token',
    POWR: 'Powerledger',
    SYS: 'Syscoin',
    CVC: 'CoviCoin',
    OXT: 'Orchid',
    RLC: 'iExec RLC',
    CFX: 'Conflux',
    ARDR: 'Ardor',
    PAXG: 'PAX Gold',
    STMX: 'StormX',
    TOMO: 'TomoChain',
    BADGER: 'Badger DAO',
    ONG: 'SoMee.Social [OLD]',
    XVS: 'Venus',
    POLS: 'Polkastarter',
    ELF: 'Elf Token',
    ENS: 'Ethereum Name Service',
    ILV: 'Illuvium',
    JASMY: 'JasmyCoin',
    PLA: 'PlayChip',
    SUPER: 'SuperCoin',
    YGG: 'Yield Guild Games',
    C98: 'Coin98',
    MBOX: 'MOBOX',
    TRIBE: 'Tribe',
    DAR: 'Mines of Dalarnia',
    KEEP: 'Keep Network',
    BNX: 'BinaryX',
    TWT: 'Trust Wallet Token',
    TLM: 'Alien Worlds',
    MASK: 'NFTX Hashmasks Index',
    FIDA: 'Bonfida',
    PUNDIX: 'Pundi X[new]',
    RGT: 'Rari Governance Token',
    KNC: 'Kyber Network Crystal v2',
    BAND: 'Band Protocol',
    KP3R: 'Keep3rV1',
    STRAX: 'Stratis',
    REP: 'Augur',
    RAD: 'Radicle',
    TRU: 'Truebit',
    ORN: 'Orion Protocol',
    LINA: 'LINA',
    NMR: 'Numeraire',
    FUN: 'FUNToken',
    EPS: 'Epanus',
    IDEX: 'IDEX',
    TVK: 'Terra Virtua Kolect',
    MIR: 'MIR COIN',
    REQ: 'Request',
    COCOS: 'Cocos-BCX',
    ANT: 'Aragon',
    SLP: 'Smooth Love Potion',
    MTL: 'Metal',
    AGLD: 'Adventure Gold',
    RIF: 'RSK Infrastructure Framework',
    MLN: 'Enzyme',
    BETA: 'PolyBeta Finance',
    GHST: 'Aavegotchi',
    SFP: 'SafePal',
    ERN: 'Ethernity Chain',
    STPT: 'Standard Tokenization Protocol',
    MCO: 'MCO',
    TKO: 'Toko Token',
    RARE: 'Rare',
    WAN: 'Wanchain',
    PHA: 'Phala Network',
    LTO: 'LTO Network',
    ATA: 'Automata Network',
    JST: 'JUST',
    ARPA: 'ARPA Chain',
    UTK: 'Utrust',
    SUN: 'Sun (New)',
    BTS: 'Bolt Share',
    IRIS: 'IRISnet',
    DODO: 'DODO',
    YFII: 'DFI.Money',
    MFT: 'MetaFace',
    BAL: 'Balancer',
    WNXM: 'Wrapped NXM',
    CLV: 'Clover Finance',
    AVA: 'Travala.com',
    LIT: 'Lition',
    BOND: 'Bonded Finance',
    FORTH: 'Ampleforth Governance Token',
    GTC: 'Gastrocoin',
    TROY: 'TROY',
    DUSK: 'Dusk Network',
    CHESS: 'ChessCoin',
    KMD: 'Komodo',
    TRB: 'Tellor',
    MITH: 'Mithril',
    RAMP: 'RAMP',
    AKRO: 'Akropolis',
    QUICK: 'QuickSwap',
    BEL: 'Bella Protocol',
    SUSD: 'Stabilize USD',
    BLZ: 'Bluzelle',
    BZRX: 'bZx Protocol',
    DIA: 'DIA',
    ALPACA: 'Alpaca Finance',
    DATA: 'Data Economy Index',
    CTK: 'CertiK',
    ADX: 'Cardanomics',
    DNT: 'district0x',
    HARD: 'Kava Lend',
    DEGO: 'Dego Finance',
    FIRO: 'Firo',
    FLM: 'Flamingo',
    KEY: 'MoMo KEY',
    MBL: 'MovieBloc',
    COS: 'Contentos',
    AION: 'Aion',
    OM: 'MANTRA DAO',
    FARM: 'Harvest Finance',
    WTC: 'Waltonchain',
    QI: 'QiDao',
    POND: 'Marlin',
    FRONT: 'Frontier',
    NBS: 'New BitShares',
    BURGER: 'Burger Swap',
    DOCK: 'Dock',
    FIO: 'FIO Protocol',
    BEAM: 'Beam',
    AUCTION: 'Bounce Token',
    PSG: 'Paris Saint-Germain Fan Token',
    TORN: 'Tornado Cash',
    VITE: 'VITE',
    GTO: 'Gifto',
    UNFI: 'Uniswap Finance',
    NULS: 'NULS',
    DREP: 'Drep [new]',
    AUTO: 'Auto',
    LAZIO: 'Lazio Fan Token',
    CVP: 'PowerPool',
    FOR: 'Fortuna Sittard Fan Token',
    PERL: 'PERL.eco',
    PNT: 'Penta',
    DEXE: 'DeXe',
    VIDT: 'VIDT Datalink',
    MDT: 'Measurable Data Token',
    WING: 'WingShop',
    CTXC: 'Cortex',
    CITY: 'City Coin',
    BAR: 'FC Barcelona Fan Token',
    TCT: 'TacoCat Token',
    HC: 'HashLand Coin',
    ACM: 'Actinium',
    ATM: 'Atletico De Madrid Fan Token',
    DF: 'dForce',
    FIS: 'Stafi',
    JUV: 'Juventus Fan Token',
    ASR: 'AS Roma Fan Token',
    OG: 'OG Fan Token',
    USDS: 'Stably USD',
    PORTO: 'FC Porto',
    BULL: 'BuySell',
    ETHUP: 'ETHUP',
    ETHBULL: '3X Long Ethereum Token',
    ETHDOWN: 'ETHDOWN',
    BTCUP: 'BTCUP',
    DOTUP: 'DOTUP',
    BTCDOWN: 'BTCDOWN',
    BNBUP: 'BNBUP',
    LTCUP: 'LTCUP',
    '1INCHUP': '1INCHUP',
    '1INCHDOWN': '1INCHDOWN',
    XRPUP: 'XRPUP',
    SUSHIUP: 'SUSHIUP',
    BNBDOWN: 'BNBDOWN',
    ADAUP: 'ADAUP',
    XRPBULL: '3x Long XRP Token',
    UNIDOWN: 'UNIDOWN',
    DOTDOWN: 'DOTDOWN',
    BEAR: 'HoneyFarm',
    LINKUP: 'LINKUP',
    ADADOWN: 'ADADOWN',
    SXPUP: 'SXPUP',
    LTCDOWN: 'LTCDOWN',
    XRPDOWN: 'XRPDOWN',
    FILUP: 'FILUP',
    FILDOWN: 'FILDOWN',
    XTZUP: 'XTZUP',
    TRXUP: 'TRXUP',
    SXPDOWN: 'SXPDOWN',
    EOSDOWN: 'EOSDOWN',
    UNIUP: 'UNIUP',
    XLMUP: 'XLMUP',
    XTZDOWN: 'XTZDOWN',
    LINKDOWN: 'LINKDOWN',
    BNBBULL: '3X Long BNB Token',
    XLMDOWN: 'XLMDOWN',
    YFIDOWN: 'YFIDOWN',
    YFIUP: 'YFIUP',
    TRXDOWN: 'TRXDOWN',
    EOSBULL: '3x Long EOS Token',
    STORM: 'Storm Token',
    XRPBEAR: '3x Short XRP Token',
    ETHBEAR: '3X Short Ethereum Token',
    EOSBEAR: '3x Short EOS Token',
    NPXS: 'Pundi X[old]',
    BNBBEAR: '3X Short BNB Token',
    AAVEUP: 'AAVEUP',
    AAVEDOWN: 'AAVEDOWN',
};
