export type Name =
    | 'Bitcoin'
    | 'Ethereum'
    | 'Binance Coin'
    | 'SOL RUNE - Rune.Game'
    | 'Cardano'
    | 'XRP'
    | 'Polkadot'
    | 'USD Coin'
    | 'Dogecoin'
    | 'Avalanche'
    | 'SHIBA INU'
    | 'Luna Coin'
    | 'Litecoin'
    | 'UNICORN Token'
    | 'Binance USD'
    | 'Chainlink'
    | 'Polygon'
    | 'Algorand'
    | 'Bitcoin Cash'
    | 'Elrond'
    | 'Stellar'
    | 'Genesis Mana'
    | 'Axie Infinity'
    | 'VeChain'
    | 'Internet Computer'
    | 'TRON'
    | 'FTX Token'
    | 'Cosmos'
    | 'THETA'
    | 'Dai'
    | 'Filecoin'
    | 'Ethereum Classic'
    | 'The Sandbox'
    | 'Fantom'
    | 'Hedera'
    | 'NEAR Protocol'
    | 'Helium'
    | 'Monero'
    | 'Tezos'
    | 'Golden Ratio Token'
    | 'Loopring'
    | 'EOS'
    | 'Flow'
    | 'Klaytn'
    | 'PancakeSwap'
    | 'Enjin Coin'
    | 'Aave'
    | 'BigONE Token'
    | 'Zcash'
    | 'Gala'
    | 'Maker'
    | 'eCash'
    | 'Kusama'
    | 'THORChain (ERC20)'
    | 'Quant'
    | 'Neo'
    | 'Amp'
    | 'Chiliz'
    | 'Stox'
    | 'Hydro Protocol'
    | 'Waves'
    | 'BitTorrent'
    | 'Dash'
    | 'Curve DAO Token'
    | 'Arweave'
    | 'Celo'
    | 'IoTeX'
    | 'Compound Coin'
    | 'Theta Fuel'
    | 'Basic Attention Token'
    | 'NEM'
    | 'WAX'
    | 'Decred'
    | 'Oasis Network'
    | 'Qtum'
    | 'Horizen'
    | 'ICON'
    | 'Mina'
    | 'Audius'
    | 'TrueUSD'
    | 'OMG Network'
    | 'Voyager Token'
    | 'Ravencoin'
    | 'yearn.finance'
    | 'Zilliqa'
    | 'SushiSwap'
    | 'Perpetual Protocol'
    | 'Livepeer'
    | 'Ankr'
    | 'Bitcoin Gold'
    | 'Siacoin'
    | 'USDP Stablecoin'
    | 'Bancor'
    | 'Synthetix'
    | 'UMA'
    | '0x'
    | 'Ren'
    | 'SKALE Network'
    | 'Moonriver'
    | 'dYdX'
    | 'Ontology'
    | 'Celer Network'
    | 'WINkLink'
    | 'Raydium'
    | 'Kava'
    | 'Serum'
    | 'IOST'
    | 'Storj'
    | 'DigiByte'
    | 'Chromia'
    | 'MyNeighborAlice'
    | '1inch Network'
    | 'Nervos Network'
    | 'Nano'
    | 'FarmPoly'
    | 'Ocean Protocol'
    | 'Gnosis'
    | 'Fetch.ai'
    | 'Injective Protocol'
    | 'NuCypher'
    | 'Mandala Exchange Token'
    | 'Hive'
    | 'Dent'
    | 'Reserve Rights'
    | 'Cartesi'
    | 'Swipe'
    | 'Lisk'
    | 'Reef'
    | 'PolyAlpha Finance'
    | 'Verge'
    | 'Origin Protocol'
    | 'WazirX'
    | 'VeThor Token'
    | 'NKN'
    | 'COTI'
    | 'BakeryToken'
    | 'Bitcoin Standard Hashrate Token'
    | 'Powerledger'
    | 'Syscoin'
    | 'CoviCoin'
    | 'Orchid'
    | 'iExec RLC'
    | 'Conflux'
    | 'Ardor'
    | 'PAX Gold'
    | 'StormX'
    | 'TomoChain'
    | 'Badger DAO'
    | 'SoMee.Social [OLD]'
    | 'Venus'
    | 'Polkastarter'
    | 'Elf Token'
    | 'Ethereum Name Service'
    | 'Illuvium'
    | 'JasmyCoin'
    | 'PlayChip'
    | 'SuperCoin'
    | 'Yield Guild Games'
    | 'Coin98'
    | 'MOBOX'
    | 'Tribe'
    | 'Mines of Dalarnia'
    | 'Keep Network'
    | 'BinaryX'
    | 'Trust Wallet Token'
    | 'Alien Worlds'
    | 'NFTX Hashmasks Index'
    | 'Bonfida'
    | 'Pundi X[new]'
    | 'Rari Governance Token'
    | 'Kyber Network Crystal v2'
    | 'Band Protocol'
    | 'Keep3rV1'
    | 'Stratis'
    | 'Augur'
    | 'Radicle'
    | 'Truebit'
    | 'Orion Protocol'
    | 'LINA'
    | 'Numeraire'
    | 'FUNToken'
    | 'Epanus'
    | 'IDEX'
    | 'Terra Virtua Kolect'
    | 'MIR COIN'
    | 'Request'
    | 'Cocos-BCX'
    | 'Aragon'
    | 'Smooth Love Potion'
    | 'Metal'
    | 'Adventure Gold'
    | 'RSK Infrastructure Framework'
    | 'Enzyme'
    | 'PolyBeta Finance'
    | 'Aavegotchi'
    | 'SafePal'
    | 'Ethernity Chain'
    | 'Standard Tokenization Protocol'
    | 'MCO'
    | 'Toko Token'
    | 'Rare'
    | 'Wanchain'
    | 'Phala Network'
    | 'LTO Network'
    | 'Automata Network'
    | 'JUST'
    | 'ARPA Chain'
    | 'Utrust'
    | 'Sun (New)'
    | 'Bolt Share'
    | 'IRISnet'
    | 'DODO'
    | 'DFI.Money'
    | 'MetaFace'
    | 'Balancer'
    | 'Wrapped NXM'
    | 'Clover Finance'
    | 'Travala.com'
    | 'Lition'
    | 'Bonded Finance'
    | 'Ampleforth Governance Token'
    | 'Gastrocoin'
    | 'TROY'
    | 'Dusk Network'
    | 'ChessCoin'
    | 'Komodo'
    | 'Tellor'
    | 'Mithril'
    | 'RAMP'
    | 'Akropolis'
    | 'QuickSwap'
    | 'Bella Protocol'
    | 'Stabilize USD'
    | 'Bluzelle'
    | 'bZx Protocol'
    | 'DIA'
    | 'Alpaca Finance'
    | 'Data Economy Index'
    | 'CertiK'
    | 'Cardanomics'
    | 'district0x'
    | 'Kava Lend'
    | 'Dego Finance'
    | 'Firo'
    | 'Flamingo'
    | 'MoMo KEY'
    | 'MovieBloc'
    | 'Contentos'
    | 'Aion'
    | 'MANTRA DAO'
    | 'Harvest Finance'
    | 'Waltonchain'
    | 'QiDao'
    | 'Marlin'
    | 'Frontier'
    | 'New BitShares'
    | 'Burger Swap'
    | 'Dock'
    | 'FIO Protocol'
    | 'Beam'
    | 'Bounce Token'
    | 'Paris Saint-Germain Fan Token'
    | 'Tornado Cash'
    | 'VITE'
    | 'Gifto'
    | 'Uniswap Finance'
    | 'NULS'
    | 'Drep [new]'
    | 'Auto'
    | 'Lazio Fan Token'
    | 'PowerPool'
    | 'Fortuna Sittard Fan Token'
    | 'PERL.eco'
    | 'Penta'
    | 'DeXe'
    | 'VIDT Datalink'
    | 'Measurable Data Token'
    | 'WingShop'
    | 'Cortex'
    | 'City Coin'
    | 'FC Barcelona Fan Token'
    | 'TacoCat Token'
    | 'HashLand Coin'
    | 'Actinium'
    | 'Atletico De Madrid Fan Token'
    | 'dForce'
    | 'Stafi'
    | 'Juventus Fan Token'
    | 'AS Roma Fan Token'
    | 'OG Fan Token'
    | 'Stably USD'
    | 'FC Porto'
    | 'BuySell'
    | 'ETHUP'
    | '3X Long Ethereum Token'
    | 'ETHDOWN'
    | 'BTCUP'
    | 'DOTUP'
    | 'BTCDOWN'
    | 'BNBUP'
    | 'LTCUP'
    | '1INCHUP'
    | '1INCHDOWN'
    | 'XRPUP'
    | 'SUSHIUP'
    | 'BNBDOWN'
    | 'ADAUP'
    | '3x Long XRP Token'
    | 'UNIDOWN'
    | 'DOTDOWN'
    | 'HoneyFarm'
    | 'LINKUP'
    | 'ADADOWN'
    | 'SXPUP'
    | 'LTCDOWN'
    | 'XRPDOWN'
    | 'FILUP'
    | 'FILDOWN'
    | 'XTZUP'
    | 'TRXUP'
    | 'SXPDOWN'
    | 'EOSDOWN'
    | 'UNIUP'
    | 'XLMUP'
    | 'XTZDOWN'
    | 'LINKDOWN'
    | '3X Long BNB Token'
    | 'XLMDOWN'
    | 'YFIDOWN'
    | 'YFIUP'
    | 'TRXDOWN'
    | '3x Long EOS Token'
    | 'Storm Token'
    | '3x Short XRP Token'
    | '3X Short Ethereum Token'
    | '3x Short EOS Token'
    | 'Pundi X[old]'
    | '3X Short BNB Token'
    | 'AAVEUP'
    | 'AAVEDOWN';
